version: '1.0'
services:
  mysql:
    container_name: mysql
    build:
      context: ./
      dockerfile: .docker/mysql/Dockerfile
    volumes:
      - './.docker/mysql/data:/var/lib/mysql:rw'
      - './.docker/mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=threeam
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --init-file=/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3307:3306'
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - '9000:9000'
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - '8080:8080'
